[package]
name = "task-mgmt-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1"
num-traits = {version = "0.2", default-features = false}
serde = {version = "1", default-features = false, features = ["derive"]}
ssmarshal = {version = "1", default-features = false}
tinyvec = "1.6"

drv-stm32h7-usart = {path = "../../drv/stm32h7-usart", features = ["h753"]}
drv-stm32xx-uid = {path = "../../drv/stm32xx-uid", features = ["family-stm32h7"]}
ringbuf = {path = "../../lib/ringbuf"}
task-net-api = {path = "../net-api", features = ["use-smoltcp"]}
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}

gateway-messages = {git = "https://github.com/oxidecomputer/omicron", rev = "5951498bbd60306bf8e73a382e6b5aaed67a7616"}

[features]
vlan = ["task-net-api/vlan"]
usart1 = []
usart2 = []
